//
// Generated by dtk
// Translation Unit: J3DJointFactory.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/J3DGraphLoader/J3DJointFactory.h"
#include "JSystem/JSupport/JSupport.h"
#include "JSystem/J3DGraphAnimator/J3DJoint.h"
#include "port/byteswap.h"

/* 802FE1A4-802FE1FC       .text __ct__15J3DJointFactoryFRC13J3DJointBlock */
J3DJointFactory::J3DJointFactory(const J3DJointBlock& jointBlock) {
    mJointInitData = JSUConvertOffsetToPtr<J3DJointInitData>(&jointBlock, (uintptr_t)jointBlock.mpJointInitData);
    mIndexTable = JSUConvertOffsetToPtr<u16>(&jointBlock, (uintptr_t)jointBlock.mpIndexTable);

#if TARGET_LITTLE_ENDIAN
    for (int i = 0; i < jointBlock.mJointNum; i++) {
        auto& index = mIndexTable[i];
        index = byteswap(index);

        auto initData = &mJointInitData[index];
        initData->mKind = byteswap(initData->mKind);
        initData->mTransformInfo.mScale = byteswap(initData->mTransformInfo.mScale);
        initData->mTransformInfo.mRotation = byteswap(initData->mTransformInfo.mRotation);
        initData->mTransformInfo.mTranslate = byteswap(initData->mTransformInfo.mTranslate);
        initData->mRadius = byteswap(initData->mRadius);
        initData->mMin = byteswap(initData->mMin);
        initData->mMax = byteswap(initData->mMax);
    }
#endif
}

/* 802FE1FC-802FE390       .text create__15J3DJointFactoryFi */
J3DJoint* J3DJointFactory::create(int jntNo) {
    J3DJoint* joint = new J3DJoint();
    joint->mJntNo = jntNo;
    joint->mKind = getKind(jntNo);
    joint->mScaleCompensate = getScaleCompensate(jntNo);
    joint->mTransformInfo = getTransformInfo(jntNo);
    joint->mRadius = getRadius(jntNo);
    joint->mMin = getMin(jntNo);
    joint->mMax = getMax(jntNo);
    joint->mMtxCalc = NULL;
    joint->mOldMtxCalc = NULL;
    if (joint->mScaleCompensate == 0xFF) {
        joint->mScaleCompensate = false;
    }
    return joint;
}
