//
// Generated by dtk
// Translation Unit: J3DModelLoader.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/J3DGraphLoader/J3DModelLoader.h"
#include "JSystem/J3DGraphLoader/J3DMaterialFactory.h"
#include "JSystem/J3DGraphLoader/J3DMaterialFactory_v21.h"
#include "JSystem/J3DGraphLoader/J3DShapeFactory.h"
#include "JSystem/J3DGraphLoader/J3DJointFactory.h"
#include "JSystem/JUtility/JUTNameTab.h"
#include "JSystem/JSupport/JSupport.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "dolphin/os/OS.h"
#include <utility>

#if TARGET_PC
static void AssignMaterialNames(const J3DMaterialTable& table) {
    auto materialName = table.getMaterialName();
    for (int i = 0; i < table.getMaterialNum(); i++) {
        auto mat = table.getMaterialNodePointer(i);
        mat->mMaterialName = materialName->getName(i);
    }
}
#endif

/* 802FB758-802FB8A4       .text load__22J3DModelLoaderDataBaseFPCvUl */
J3DModelData* J3DModelLoaderDataBase::load(const void* i_data, u32 i_flags) {
    if (i_data == NULL) {
        return NULL;
    }
    const JUTDataFileHeader* fileHeader = (const JUTDataFileHeader*)i_data;
    if (fileHeader->mMagic == 'J3D1' && fileHeader->mType == 'bmd1') {
        return NULL;
    }
    if (fileHeader->mMagic == 'J3D2' && fileHeader->mType == 'bmd2') {
        J3DModelLoader_v21 loader;
        return loader.load(i_data, i_flags);
    }
    if (fileHeader->mMagic == 'J3D2' && fileHeader->mType == 'bmd3') {
        J3DModelLoader_v26 loader;
        return loader.load(i_data, i_flags);
    }
    return NULL;
}

/* 802FB8A4-802FB94C       .text loadMaterialTable__22J3DModelLoaderDataBaseFPCv */
J3DMaterialTable* J3DModelLoaderDataBase::loadMaterialTable(const void* i_data) {
    if (!i_data) {
        return NULL;
    }
    const JUTDataFileHeader* fileHeader = (const JUTDataFileHeader*)i_data;
    if (fileHeader->mMagic == 'J3D2' && fileHeader->mType == 'bmt3') {
        J3DModelLoader_v26 loader;
        return loader.loadMaterialTable(i_data);
    }
    return NULL;
}

/* 802FB94C-802FBA04       .text loadBinaryDisplayList__22J3DModelLoaderDataBaseFPCvUl */
J3DModelData* J3DModelLoaderDataBase::loadBinaryDisplayList(const void* i_data, u32 i_flags) {
    if (!i_data) {
        return NULL;
    }
    const JUTDataFileHeader* fileHeader = (const JUTDataFileHeader*)i_data;
    if (fileHeader->mMagic == 'J3D2' && (fileHeader->mType == 'bdl3' || fileHeader->mType == 'bdl4')) {
        J3DModelLoader_v26 loader;
        return loader.loadBinaryDisplayList(i_data, i_flags);
    }
    return NULL;
}

/* 802FBA04-802FBCC4       .text load__14J3DModelLoaderFPCvUl */
J3DModelData* J3DModelLoader::load(const void* i_data, u32 i_flags) {
    JKRGetCurrentHeap()->getTotalFreeSize();
    mpModelData = new J3DModelData();
    mpModelData->clear();
    mpModelData->mBinary = i_data;
    mpModelData->setModelDataType(0);
    mpMaterialTable = &mpModelData->mMaterialTable;
    const JUTDataFileHeader* data = (JUTDataFileHeader*)i_data;
    const JUTDataBlockHeader* block = &data->mFirstBlock;
    for (u32 block_no = 0; block_no < data->mBlockNum; block_no++) {
        switch (block->mType) {
            case 'INF1':
                readInformation((J3DModelInfoBlock*)block, (u32)i_flags); // cast fixes regalloc
                break;
            case 'VTX1':
                readVertex((J3DVertexBlock*)block);
                break;
            case 'EVP1':
                readEnvelop((J3DEnvelopBlock*)block);
                break;
            case 'DRW1':
                readDraw((J3DDrawBlock*)block);
                break;
            case 'JNT1':
                readJoint((J3DJointBlock*)block);
                break;
            case 'MAT3':
                readMaterial((J3DMaterialBlock*)block, i_flags);
                break;
            case 'MAT2':
                readMaterial_v21((J3DMaterialBlock_v21*)block, i_flags);
                break;
            case 'SHP1':
                readShape((J3DShapeBlock*)block, i_flags);
                break;
            case 'TEX1':
                readTexture((J3DTextureBlock*)block);
                break;
            default:
                OSReport("Unknown data block\n");
                break;
        }
        block = (JUTDataBlockHeader*)((u8*)block + block->mSize);
    }
    const J3DModelHierarchy* hierarchy = mpModelData->getHierarchy();
    mpModelData->makeHierarchy(NULL, &hierarchy);
    mpModelData->sortVcdVatCmd();
    setupBBoardInfo();
    if (mpModelData->getFlag() & 0x100) {
        for (u16 shape_no = 0; shape_no < mpModelData->getShapeNum(); shape_no++) {
            mpModelData->getShapeNodePointer(shape_no)->onFlag(0x200);
        }
    }
#if TARGET_PC
    AssignMaterialNames(*mpMaterialTable);
#endif
    return mpModelData;
}

/* 802FBCC4-802FBE24       .text loadMaterialTable__14J3DModelLoaderFPCv */
J3DMaterialTable* J3DModelLoader::loadMaterialTable(const void* i_data) {
    mpMaterialTable = new J3DMaterialTable();
    mpMaterialTable->clear();
    const JUTDataFileHeader* data = (JUTDataFileHeader*)i_data;
    const JUTDataBlockHeader* block = &data->mFirstBlock;
    for (u32 block_no = 0; block_no < data->mBlockNum; block_no++) {
        switch (block->mType) {
            case 'MAT3':
                readMaterialTable((J3DMaterialBlock*)block, 0x51100000);
                break;
            case 'MAT2':
                readMaterialTable_v21((J3DMaterialBlock_v21*)block, 0x51100000);
                break;
            case 'TEX1':
                readTextureTable((J3DTextureBlock*)block);
                break;
            default:
                OSReport("Unknown data block\n");
                break;
        }
        block = (JUTDataBlockHeader*)((u8*)block + block->mSize);
    }
    if (mpMaterialTable->getTexture() == NULL) {
        mpMaterialTable->setTexture(new J3DTexture(0, NULL));
    }
#if TARGET_PC
    AssignMaterialNames(*mpMaterialTable);
#endif
    return mpMaterialTable;
}

/* 802FBE24-802FC0CC       .text loadBinaryDisplayList__14J3DModelLoaderFPCvUl */
J3DModelData* J3DModelLoader::loadBinaryDisplayList(const void* i_data, u32 i_flags) {
    mpModelData = new J3DModelData();
    mpModelData->clear();
    mpModelData->mBinary = i_data;
    mpModelData->setModelDataType(1);
    mpMaterialTable = &mpModelData->mMaterialTable;
    const JUTDataFileHeader* data = (JUTDataFileHeader*)i_data;
    const JUTDataBlockHeader* block = &data->mFirstBlock;
    for (u32 block_no = 0; block_no < data->mBlockNum; block_no++) {
        switch (block->mType) {
            case 'INF1':
                readInformation((J3DModelInfoBlock*)block, (u32)i_flags); // cast fixes regalloc
                break;
            case 'VTX1':
                readVertex((J3DVertexBlock*)block);
                break;
            case 'EVP1':
                readEnvelop((J3DEnvelopBlock*)block);
                break;
            case 'DRW1':
                readDraw((J3DDrawBlock*)block);
                break;
            case 'JNT1':
                readJoint((J3DJointBlock*)block);
                break;
            case 'SHP1':
                readShape((J3DShapeBlock*)block, i_flags);
                break;
            case 'TEX1':
                readTexture((J3DTextureBlock*)block);
                break;
            case 'MDL3':
                readMaterialDL((J3DMaterialDLBlock*)block, i_flags);
                modifyMaterial(i_flags);
                break;
            case 'MAT3': {
                u32 matFlags = 0x50100000;
                matFlags |= i_flags & 0x03000000;
                mpMaterialBlock = (J3DMaterialBlock*)block;
                u32 matType = getBdlFlag_MaterialType(i_flags);
                if (matType == 0) {
                    readMaterial((J3DMaterialBlock*)block, matFlags);
                } else if (matType == 0x2000) {
                    readPatchedMaterial((J3DMaterialBlock*)block, matFlags);
                }
                break;
            }
            default:
                OSReport("Unknown data block\n");
                break;
        }
        block = (JUTDataBlockHeader*)((u8*)block + block->mSize);
    }
    J3DModelHierarchy const* hierarchy = mpModelData->getHierarchy();
    mpModelData->makeHierarchy(NULL, &hierarchy);
    mpModelData->sortVcdVatCmd();
    setupBBoardInfo();
    mpModelData->indexToPtr();
#if TARGET_PC
    AssignMaterialNames(*mpMaterialTable);
#endif
    return mpModelData;
}

/* 802FC0CC-802FC234       .text setupBBoardInfo__14J3DModelLoaderFv */
void J3DModelLoader::setupBBoardInfo() {
    for (u16 i = 0; i < mpModelData->getJointNum(); i++) {
        J3DMaterial* mesh = mpModelData->getJointNodePointer(i)->getMesh();
        if (mesh != NULL) {
            u16 shape_index = mesh->getShape()->getIndex();
            BE(u16)* index_table = JSUConvertOffsetToPtr<BE(u16)>(mpShapeBlock, (uintptr_t)mpShapeBlock->mpIndexTable);
            J3DShapeInitData* shape_init_data =
                JSUConvertOffsetToPtr<J3DShapeInitData>(mpShapeBlock, (uintptr_t)mpShapeBlock->mpShapeInitData);
            J3DJoint* joint;
            switch (shape_init_data[index_table[shape_index]].mShapeMtxType) {
                case 0:
                    joint = mpModelData->getJointNodePointer(i);
                    joint->setMtxType(0);
                    break;
                case 1:
                    joint = mpModelData->getJointNodePointer(i);
                    joint->setMtxType(1);
                    mpModelData->mbHasBillboard = true;
                    break;
                case 2:
                    joint = mpModelData->getJointNodePointer(i);
                    joint->setMtxType(2);
                    mpModelData->mbHasBillboard = true;
                    break;
                case 3:
                    joint = mpModelData->getJointNodePointer(i);
                    joint->setMtxType(0);
                    break;
                default:
                    OSReport("WRONG SHAPE MATRIX TYPE (__FILE__)\n");
                    break;
            }
        }
    }
}

/* 802FC234-802FC3E4       .text readInformation__14J3DModelLoaderFPC17J3DModelInfoBlockUl */
void J3DModelLoader::readInformation(const J3DModelInfoBlock* i_block, u32 i_flags) {
    mpModelData->mFlags = i_flags | i_block->mFlags;
    mpModelData->getJointTree().setFlag(mpModelData->mFlags);
    J3DMtxCalc* mtx_calc = NULL;
    switch (mpModelData->mFlags & 0xF) {
        case 0: // TODO: enum for mtxcalc type (and other load flags)
            mtx_calc = new J3DMtxCalcBasic();
            break;
        case 1:
            mtx_calc = new J3DMtxCalcSoftimage();
            break;
        case 2:
            mtx_calc = new J3DMtxCalcMaya();
            break;
    }
    mpModelData->setBasicMtxCalc(mtx_calc);
    mpModelData->mVertexData.mPacketNum = i_block->mPacketNum;
    mpModelData->getVertexData().mVtxNum = i_block->mVtxNum;
    mpModelData->setHierarchy(JSUConvertOffsetToPtr<J3DModelHierarchy>(i_block, i_block->mpHierarchy));

#if TARGET_PC
    mpModelData->getVertexData().mHasReadInformation = true;
#endif
}

#if TARGET_PC
static GXVtxAttrFmtList getFmt(GXVtxAttrFmtList* i_fmtList, GXAttr i_attr) {
    for (; i_fmtList->attr != GX_VA_NULL; i_fmtList++) {
        if (i_fmtList->attr == i_attr) {
            return *i_fmtList;
        }
    }

    OSPanic(__FILE__, __LINE__, "Unable to find vertex attribute format!");
}
#endif

/* 802FC3E4-802FC410       .text getFmtType__FP17_GXVtxAttrFmtList7_GXAttr */
static GXCompType getFmtType(GXVtxAttrFmtList* i_fmtList, GXAttr i_attr) {
    for (; i_fmtList->attr != GX_VA_NULL; i_fmtList++) {
        if (i_fmtList->attr == i_attr) {
            return i_fmtList->type;
        }
    }
    return GX_F32;
}

/* 802FC410-802FC630       .text readVertex__14J3DModelLoaderFPC14J3DVertexBlock */
void J3DModelLoader::readVertex(const J3DVertexBlock* i_block) {
    J3DVertexData& vertex_data = mpModelData->getVertexData();
    vertex_data.mVtxAttrFmtList =
        JSUConvertOffsetToPtr<GXVtxAttrFmtList>(i_block, i_block->mpVtxAttrFmtList);
    vertex_data.mVtxPosArray = JSUConvertOffsetToPtr<void>(i_block, i_block->mpVtxPosArray);
    vertex_data.mVtxNrmArray = JSUConvertOffsetToPtr<void>(i_block, i_block->mpVtxNrmArray);
    vertex_data.mVtxNBTArray = JSUConvertOffsetToPtr<void>(i_block, i_block->mpVtxNBTArray);
    for (int i = 0; i < 2; i++) {
        vertex_data.mVtxColorArray[i] =
            (GXColor*)JSUConvertOffsetToPtr<void>(i_block, i_block->mpVtxColorArray[i]);
    }
    for (int i = 0; i < 8; i++) {
        vertex_data.mVtxTexCoordArray[i] =
            JSUConvertOffsetToPtr<void>(i_block, i_block->mpVtxTexCoordArray[i]);
    }

#if TARGET_LITTLE_ENDIAN
    for (GXVtxAttrFmtList* attrFmt = vertex_data.mVtxAttrFmtList;; attrFmt++) {
        *attrFmt = byteswap(*attrFmt);

        if (attrFmt->attr == GX_VA_NULL) {
            break;
        }
    }
#endif

    GXCompType nrm_type = getFmtType(vertex_data.mVtxAttrFmtList, GX_VA_NRM);
    u32 nrm_size = nrm_type == GX_F32 ? 12 : 6;

    void* nrm_end = NULL;
    if (vertex_data.mVtxNBTArray != NULL) {
        nrm_end = vertex_data.mVtxNBTArray;
    } else if (vertex_data.mVtxColorArray[0] != NULL) {
        nrm_end = vertex_data.mVtxColorArray[0];
    } else if (vertex_data.mVtxTexCoordArray[0] != NULL) {
        nrm_end = vertex_data.mVtxTexCoordArray[0];
    }

    if (vertex_data.mVtxNrmArray == NULL) {
        vertex_data.mNrmNum = 0;
    } else if (nrm_end != NULL) {
        vertex_data.mNrmNum = ((uintptr_t)nrm_end - (uintptr_t)vertex_data.mVtxNrmArray) / nrm_size + 1;
    } else {
        vertex_data.mNrmNum = (i_block->mSize - (uintptr_t)i_block->mpVtxNrmArray) / nrm_size + 1;
    }

    void* color0_end = NULL;
    if (vertex_data.mVtxColorArray[1] != NULL) {
        color0_end = vertex_data.mVtxColorArray[1];
    } else if (vertex_data.mVtxTexCoordArray[0] != NULL) {
        color0_end = vertex_data.mVtxTexCoordArray[0];
    }

    if (vertex_data.mVtxColorArray[0] == NULL) {
        vertex_data.mColNum = 0;
    } else if (color0_end != NULL) {
        vertex_data.mColNum = ((uintptr_t)color0_end - (uintptr_t)vertex_data.mVtxColorArray[0]) / 4 + 1;
    } else {
        vertex_data.mColNum = (i_block->mSize - (uintptr_t)i_block->mpVtxColorArray[0]) / 4 + 1;
    }

    if (vertex_data.mVtxTexCoordArray[0] == NULL) {
        vertex_data.mTexCoordNum = 0;
    } else {
        vertex_data.mTexCoordNum = (i_block->mSize - (uintptr_t)i_block->mpVtxTexCoordArray[0]) / 8 + 1;
    }

#if TARGET_PC
    readVertexData(*i_block, vertex_data);
#endif
}

#if TARGET_PC

// Approach taken from here:
// https://github.com/zeldaret/tp/blob/6c72b91f8e477ee94ccdc56b94605140e9f2abd6/libs/JSystem/src/J3DGraphBase/J3DShape.cpp#L156-L211

template <typename T> static void FixArrayEndian(T* arrayStart, T* arrayEnd) {
#if TARGET_LITTLE_ENDIAN
    u32 itemCount = ((u8*)arrayEnd - (u8*)arrayStart) / sizeof(T);
    for (u32 i = 0; i < itemCount; i++) {
        arrayStart[i] = byteswap(arrayStart[i]);
    }
#endif
}

static void FixArrayEndian_24(void* arrayStart, void* arrayEnd) {
#if TARGET_LITTLE_ENDIAN
    for (u8* work = (u8*)arrayStart; work != (u8*)arrayEnd; work += 3) {
        std::swap(work[0], work[2]);
    }
#endif
}

static void FixArrayEndian(void* arrayStart, void* arrayEnd, u32 stride) {
    switch (stride) {
        case 1:
            // Nothing needs to happen here!
            break;
        case 2:
            FixArrayEndian<u16>((u16*)arrayStart, (u16*)arrayEnd);
            break;
        case 3:
            FixArrayEndian_24(arrayStart, arrayEnd);
            break;
        case 4:
            FixArrayEndian<u32>((u32*)arrayStart, (u32*)arrayEnd);
            break;
        default:
            OSPanic(__FILE__, __LINE__, "Unknown component type?");
    }
}

static GXAttr VertexBlockAttrOrder[13] = {
    GX_VA_POS,
    GX_VA_NRM,
    GX_VA_NBT,
    GX_VA_CLR0,
    GX_VA_CLR1,
    GX_VA_TEX0,
    GX_VA_TEX1,
    GX_VA_TEX2,
    GX_VA_TEX3,
    GX_VA_TEX4,
    GX_VA_TEX5,
    GX_VA_TEX6,
    GX_VA_TEX7,
};

static void* GetDataEnd(const J3DVertexBlock& block, int start) {
    const BE(u32)* attrPtrBase = &block.mpVtxPosArray;

    for (int i = start + 1; i < ARRAY_SIZE(VertexBlockAttrOrder); i++) {
        if (attrPtrBase[i] != 0) {
            return JSUConvertOffsetToPtr<void>(&block, attrPtrBase[i]);
        }
    }

    return JSUConvertOffsetToPtr<void>(&block, block.mSize);
}

auto StrideForData(GXAttr attr, GXCompType type, GXCompCnt cnt) -> std::pair<u32, u32> {
    auto CompTypeStrideRaw = [&] {
        if (type == GX_F32)
            return 4;
        else if (type == GX_U16 || type == GX_S16)
            return 2;
        else
            return 1;
    };

    auto HandleColor = [&]() -> std::pair<u32, u32> {
        if (type == GX_RGB565)
            return {1, 2}; // u16[1]
        else if (type == GX_RGB8)
            return {3, 1}; // u8[3]
        else if (type == GX_RGBX8)
            return {4, 1}; // u8[4]
        else if (type == GX_RGBA4)
            return {1, 2}; // u16[1]
        else if (type == GX_RGBA6)
            return {3, 1}; // u8[3]
        else if (type == GX_RGBA8)
            return {4, 1}; // u8[4]
    };

    auto CompCnt = [&] {
        if (attr == GX_VA_POS) {
            return cnt == GX_POS_XY ? 2 : 3;
        } else if (attr == GX_VA_NRM) {
            return cnt == GX_NRM_XYZ ? 3 : 9; // NBT3 is lies
        } else if (attr >= GX_VA_CLR0 && attr <= GX_VA_CLR1) {
            return cnt == GX_CLR_RGB ? 3 : 4; // clr is special anyway
        } else if (attr >= GX_VA_TEX0 && attr <= GX_VA_TEX7) {
            return cnt == GX_TEX_S ? 1 : 2;
        } else {
            JUT_ASSERT(1234, false);
        }
    };

    if (attr >= GX_VA_CLR0 && attr <= GX_VA_CLR1) {
        return HandleColor();
    } else {
        int compCnt = CompCnt();
        int compStride = CompTypeStrideRaw();
        return {compCnt, compStride};
    }
}

void J3DModelLoader::readVertexData(const J3DVertexBlock& block, J3DVertexData& data) {
    if (!data.mHasReadInformation) {
        OSPanic(__FILE__, __LINE__, "Model has VTX1 before INF1?");
    }

    const BE(u32)* attrPtrBase = &block.mpVtxPosArray;
    for (int i = 0; i < ARRAY_SIZE(VertexBlockAttrOrder); i++) {
        GXAttr attr = VertexBlockAttrOrder[i];

        if (attrPtrBase[i] == 0) {
            continue;
        }

        GXVtxAttrFmtList fmt = getFmt(data.mVtxAttrFmtList, attr);

        void* startAddr = JSUConvertOffsetToPtr<void>(&block, attrPtrBase[i]);
        void* endAddr = GetDataEnd(block, i);
        auto [compCnt, compStride] = StrideForData(attr, fmt.type, fmt.cnt);
        u32 vertStride = compStride * compCnt;
        data.mVtxArrStride[attr - GX_VA_POS] = vertStride;

        u32 addrDiff = u32((u8*)endAddr - (u8*)startAddr);
        u32 num = addrDiff / vertStride;
        data.mVtxArrNum[attr - GX_VA_POS] = num;
        FixArrayEndian(startAddr, endAddr, compStride);

        if (attr == GX_VA_POS) {
            // can be a little off due to 0x20 alignment, account for that
            // u32 expect = ((data.mVtxNum * vertStride) + 0x1F) & ~0x1F;
            // JUT_ASSERT(1234, expect == addrDiff);
        } else if (attr == GX_VA_NRM) {
            data.mNrmNum = num;
        } else if (attr == GX_VA_CLR0) {
            data.mColNum = num;
        } else if (attr == GX_VA_TEX0) {
            data.mTexCoordNum = num;
        }
    }
}
#endif

/* 802FC630-802FC6C0       .text readEnvelop__14J3DModelLoaderFPC15J3DEnvelopBlock */
void J3DModelLoader::readEnvelop(const J3DEnvelopBlock* i_block) {
    mpModelData->getJointTree().mWEvlpMtxNum = i_block->mWEvlpMtxNum;
    mpModelData->getJointTree().mWEvlpMixMtxNum =
        JSUConvertOffsetToPtr<u8>(i_block, i_block->mpWEvlpMixMtxNum);
    mpModelData->getJointTree().mWEvlpMixMtxIndex =
        JSUConvertOffsetToPtr<BE(u16)>(i_block, i_block->mpWEvlpMixMtxIndex);
    mpModelData->getJointTree().mWEvlpMixWeight =
        JSUConvertOffsetToPtr<BE(f32)>(i_block, i_block->mpWEvlpMixWeight);
    mpModelData->getJointTree().mInvJointMtx =
        JSUConvertOffsetToPtr<BE(Mtx)>(i_block, i_block->mpInvJointMtx);
}

/* 802FC6C0-802FC750       .text readDraw__14J3DModelLoaderFPC12J3DDrawBlock */
void J3DModelLoader::readDraw(const J3DDrawBlock* i_block) {
    J3DJointTree& joint_tree = mpModelData->getJointTree();
    joint_tree.mDrawMtxData.mEntryNum = i_block->mMtxNum;
    joint_tree.mDrawMtxData.mDrawMtxFlag = JSUConvertOffsetToPtr<u8>(i_block, i_block->mpDrawMtxFlag);
    joint_tree.mDrawMtxData.mDrawMtxIndex = JSUConvertOffsetToPtr<BE(u16)>(i_block, i_block->mpDrawMtxIndex);
    u16 i;
    for (i = 0; i < joint_tree.mDrawMtxData.mEntryNum; i++) {
        if (joint_tree.mDrawMtxData.mDrawMtxFlag[i] == 1) {
            break;
        }
    }
    joint_tree.mDrawMtxData.mDrawFullWgtMtxNum = i;
}

/* 802FC750-802FC834       .text readJoint__14J3DModelLoaderFPC13J3DJointBlock */
void J3DModelLoader::readJoint(const J3DJointBlock* i_block) {
    J3DJointFactory factory(*i_block);
    mpModelData->getJointTree().mJointNum = i_block->mJointNum;
    if (i_block->mpNameTable != NULL) {
        mpModelData->getJointTree().mJointName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpModelData->getJointTree().mJointName = NULL;
    }
    mpModelData->getJointTree().mJointNodePointer =
        new J3DJoint*[mpModelData->getJointTree().mJointNum];
    for (u16 i = 0; i < mpModelData->getJointTree().getJointNum(); i++) {
        mpModelData->getJointTree().mJointNodePointer[i] = factory.create(i);
    }
}

/* 802FC834-802FCAB0       .text readMaterial__18J3DModelLoader_v26FPC16J3DMaterialBlockUl */
void J3DModelLoader_v26::readMaterial(const J3DMaterialBlock* i_block, u32 i_flags) {
    J3DMaterialFactory factory(*i_block);
    mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
    mpMaterialTable->mUniqueMatNum = factory.countUniqueMaterials();
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mMaterialName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mMaterialName = NULL;
    }
    mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
    if (i_flags & 0x200000) {
        mpMaterialTable->mMaterialBase = new (0x20) J3DMaterial[mpMaterialTable->mUniqueMatNum];
    } else {
        mpMaterialTable->mMaterialBase = NULL;
    }
    if (i_flags & 0x200000) {
        for (u16 i = 0; i < mpMaterialTable->mUniqueMatNum; i++) {
            factory.create(&mpMaterialTable->mMaterialBase[i],
                           J3DMaterialFactory::MATERIAL_TYPE_NORMAL, i, i_flags);
            mpMaterialTable->mMaterialBase[i].mDiffFlag = (uintptr_t)&mpMaterialTable->mMaterialBase[i] >> 4;
        }
    }
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i] =
            factory.create(NULL, J3DMaterialFactory::MATERIAL_TYPE_NORMAL, i, i_flags);
    }
    if (i_flags & 0x200000) {
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
                (uintptr_t)&mpMaterialTable->mMaterialBase[factory.getMaterialID(i)] >> 4;
            mpMaterialTable->mMaterialNodePointer[i]->mpOrigMaterial =
                &mpMaterialTable->mMaterialBase[factory.getMaterialID(i)];
        }
    } else {
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
                ((uintptr_t)mpMaterialTable->mMaterialNodePointer >> 4) + factory.getMaterialID(i);
        }
    }
}

/* 802FCAB0-802FCD14       .text readMaterial_v21__18J3DModelLoader_v21FPC20J3DMaterialBlock_v21Ul */
void J3DModelLoader_v21::readMaterial_v21(const J3DMaterialBlock_v21* i_block, u32 i_flags) {
    J3DMaterialFactory_v21 factory(*i_block);
    mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
    mpMaterialTable->mUniqueMatNum = factory.countUniqueMaterials();
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mMaterialName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mMaterialName = NULL;
    }
    mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
    if (i_flags & 0x200000) {
        mpMaterialTable->mMaterialBase = new (0x20) J3DMaterial[mpMaterialTable->mUniqueMatNum];
    } else {
        mpMaterialTable->mMaterialBase = NULL;
    }
    if (i_flags & 0x200000) {
        for (u16 i = 0; i < mpMaterialTable->mUniqueMatNum; i++) {
            factory.create(&mpMaterialTable->mMaterialBase[i], i, i_flags);
            mpMaterialTable->mMaterialBase[i].mDiffFlag = (uintptr_t)&mpMaterialTable->mMaterialBase[i] >> 4;
        }
    }
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i] = factory.create(NULL, i, i_flags);
    }
    if (i_flags & 0x200000) {
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
                (uintptr_t)&mpMaterialTable->mMaterialBase[factory.getMaterialID(i)] >> 4;
            mpMaterialTable->mMaterialNodePointer[i]->mpOrigMaterial =
                &mpMaterialTable->mMaterialBase[factory.getMaterialID(i)];
        }
    } else {
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag = 0xC0000000;
        }
    }
}

/* 802FCD14-802FCE50       .text readShape__14J3DModelLoaderFPC13J3DShapeBlockUl */
void J3DModelLoader::readShape(const J3DShapeBlock* i_block, u32 i_flags) {
    mpShapeBlock = i_block;
    J3DShapeFactory factory(*i_block);
    mpModelData->mShapeTable.mShapeNum = i_block->mShapeNum;
    if (i_block->mpNameTable != NULL) {
        mpModelData->mName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpModelData->mName = NULL;
    }
    mpModelData->mShapeTable.mShapeNodePointer = new J3DShape*[mpModelData->mShapeTable.mShapeNum];
    factory.allocVcdVatCmdBuffer(mpModelData->mShapeTable.mShapeNum);
    J3DModelHierarchy const* hierarchy_entry = mpModelData->getHierarchy();
    GXVtxDescList* vtx_desc_list = NULL;
    for (; hierarchy_entry->mType != 0; hierarchy_entry++) {
        if (hierarchy_entry->mType == 0x12) {
            mpModelData->mShapeTable.mShapeNodePointer[hierarchy_entry->mValue] =
                factory.create(hierarchy_entry->mValue, i_flags, vtx_desc_list);
            vtx_desc_list = factory.getVtxDescList(hierarchy_entry->mValue);
        }
    }
}

/* 802FCE50-802FCF14       .text readTexture__14J3DModelLoaderFPC15J3DTextureBlock */
void J3DModelLoader::readTexture(const J3DTextureBlock* i_block) {
    u16 texture_num = i_block->mTextureNum;
    ResTIMG* texture_res = JSUConvertOffsetToPtr<ResTIMG>(i_block, i_block->mpTextureRes);
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mTextureName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mTextureName = NULL;
    }
    mpMaterialTable->mTexture = new J3DTexture(texture_num, texture_res);
}

/* 802FCF14-802FD050       .text readMaterialTable__18J3DModelLoader_v26FPC16J3DMaterialBlockUl */
void J3DModelLoader_v26::readMaterialTable(const J3DMaterialBlock* i_block, u32 i_flags) {
    J3DMaterialFactory factory(*i_block);
    mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mMaterialName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mMaterialName = NULL;
    }
    mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i] =
            factory.create(NULL, J3DMaterialFactory::MATERIAL_TYPE_NORMAL, i, i_flags);
    }
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
            (uintptr_t)mpMaterialTable->mMaterialNodePointer + factory.getMaterialID(i);
    }
}

/* 802FD050-802FD18C       .text readMaterialTable_v21__18J3DModelLoader_v21FPC20J3DMaterialBlock_v21Ul */
void J3DModelLoader_v21::readMaterialTable_v21(const J3DMaterialBlock_v21* i_block, u32 i_flags) {
    J3DMaterialFactory_v21 factory(*i_block);
    mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mMaterialName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mMaterialName = NULL;
    }
    mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i] =
            factory.create(NULL, i, i_flags);
    }
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
            ((uintptr_t)mpMaterialTable->mMaterialNodePointer >> 4) + factory.getMaterialID(i);
    }
}

/* 802FD18C-802FD250       .text readTextureTable__14J3DModelLoaderFPC15J3DTextureBlock */
void J3DModelLoader::readTextureTable(const J3DTextureBlock* i_block) {
    u16 texture_num = i_block->mTextureNum;
    ResTIMG* texture_res = JSUConvertOffsetToPtr<ResTIMG>(i_block, i_block->mpTextureRes);
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mTextureName = new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mTextureName = NULL;
    }
    mpMaterialTable->mTexture = new J3DTexture(texture_num, texture_res);
}

/* 802FD250-802FD390       .text readPatchedMaterial__14J3DModelLoaderFPC16J3DMaterialBlockUl */
void J3DModelLoader::readPatchedMaterial(const J3DMaterialBlock* i_block, u32 i_flags) {
    J3DMaterialFactory factory(*i_block);
    mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
    mpMaterialTable->mUniqueMatNum = factory.countUniqueMaterials();
    if (i_block->mpNameTable != NULL) {
        mpMaterialTable->mMaterialName =
            new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
    } else {
        mpMaterialTable->mMaterialName = NULL;
    }
    mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
    mpMaterialTable->mMaterialBase = NULL;
    for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
        mpMaterialTable->mMaterialNodePointer[i] =
            factory.create(NULL, J3DMaterialFactory::MATERIAL_TYPE_PATCHED, i, i_flags);
        mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag =
            ((uintptr_t)mpMaterialTable->mMaterialNodePointer >> 4) + factory.getMaterialID(i);
    }
}

/* 802FD390-802FD548       .text readMaterialDL__14J3DModelLoaderFPC18J3DMaterialDLBlockUl */
void J3DModelLoader::readMaterialDL(const J3DMaterialDLBlock* i_block, u32 i_flags) {
    J3DMaterialFactory factory(*i_block);
    if (mpMaterialTable->mMaterialNum == 0) {
        mpMaterialTable->mbIsLocked = 1;
        mpMaterialTable->mMaterialNum = i_block->mMaterialNum;
        mpMaterialTable->mUniqueMatNum = i_block->mMaterialNum;
        if (i_block->mpNameTable != NULL) {
            mpMaterialTable->mMaterialName =
                new JUTNameTab(JSUConvertOffsetToPtr<ResNTAB>(i_block, i_block->mpNameTable));
        } else {
            mpMaterialTable->mMaterialName = NULL;
        }
        mpMaterialTable->mMaterialNodePointer = new J3DMaterial*[mpMaterialTable->mMaterialNum];
        mpMaterialTable->mMaterialBase = NULL;
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i] = factory.create(
                NULL, J3DMaterialFactory::MATERIAL_TYPE_LOCKED, i, (u32)i_flags // cast fixes regalloc
            );
        }
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i]->mDiffFlag = 0xC0000000;
        }
    } else {
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            mpMaterialTable->mMaterialNodePointer[i] = factory.create(
                mpMaterialTable->mMaterialNodePointer[i],
                J3DMaterialFactory::MATERIAL_TYPE_LOCKED, i, (u32)i_flags // cast fixes regalloc
            );
        }
    }
}

/* 802FD548-802FD5C4       .text modifyMaterial__14J3DModelLoaderFUl */
void J3DModelLoader::modifyMaterial(u32 i_flags) {
    if (i_flags & 0x2000) {
        J3DMaterialFactory factory(*mpMaterialBlock);
        for (u16 i = 0; i < mpMaterialTable->mMaterialNum; i++) {
            factory.modifyPatchedCurrentMtx(mpMaterialTable->mMaterialNodePointer[i], i);
        }
    }
}
