//
// Generated by dtk
// Translation Unit: data.cpp
//

#include "JSystem/JSystem.h" // IWYU pragma: keep

#include "JSystem/JMessage/data.h"

namespace JMessage {
namespace data {
const char ga4cSignature[4] = {'M', 'E', 'S', 'G'};
} // namespace data
} // namespace JMessage
