//
// Generated by dtk
// Translation Unit: d_a_warpmj.cpp
//

#include "d/dolzel_rel.h" // IWYU pragma: keep
#include "global.h"
#include "d/actor/d_a_warpmj.h"

/* 00000078-000000A8       .text _delete__10daWarpmj_cFv */
bool daWarpmj_c::_delete() {
    NOT_IMPLEMENTED;
    return 0;
}

/* 000000A8-000000C8       .text CheckCreateHeap__FP10fopAc_ac_c */
static BOOL CheckCreateHeap(fopAc_ac_c*) {
    NOT_IMPLEMENTED;
    return 0;
}

/* 000000C8-00000454       .text CreateHeap__10daWarpmj_cFv */
void daWarpmj_c::CreateHeap() {
    NOT_IMPLEMENTED;
}

/* 0000049C-00000630       .text CreateInit__10daWarpmj_cFv */
void daWarpmj_c::CreateInit() {
    NOT_IMPLEMENTED;
}

/* 00000630-00000778       .text _create__10daWarpmj_cFv */
cPhs_State daWarpmj_c::_create() {
    NOT_IMPLEMENTED;
    return 0;
}

/* 00000778-0000084C       .text set_mtx__10daWarpmj_cFv */
void daWarpmj_c::set_mtx() {
    NOT_IMPLEMENTED;
}

/* 0000084C-00000990       .text _execute__10daWarpmj_cFv */
bool daWarpmj_c::_execute() {
    NOT_IMPLEMENTED;
    return 0;
}

/* 00000990-000009D4       .text normal_execute__10daWarpmj_cFv */
void daWarpmj_c::normal_execute() {
    NOT_IMPLEMENTED;
}

/* 000009D4-00000A60       .text demo_execute__10daWarpmj_cFv */
void daWarpmj_c::demo_execute() {
    NOT_IMPLEMENTED;
}

/* 00000A60-00000B7C       .text demo_proc__10daWarpmj_cFv */
void daWarpmj_c::demo_proc() {
    NOT_IMPLEMENTED;
}

/* 00000B7C-00000B80       .text initWait__10daWarpmj_cFi */
void daWarpmj_c::initWait(int) {
    NOT_IMPLEMENTED;
}

/* 00000B80-00000BA4       .text actWait__10daWarpmj_cFi */
void daWarpmj_c::actWait(int) {
    NOT_IMPLEMENTED;
}

/* 00000BA4-00000C14       .text initWarp__10daWarpmj_cFi */
void daWarpmj_c::initWarp(int) {
    NOT_IMPLEMENTED;
}

/* 00000C14-00000C38       .text actWarp__10daWarpmj_cFi */
void daWarpmj_c::actWarp(int) {
    NOT_IMPLEMENTED;
}

/* 00000C38-00000C94       .text initWarpArrive__10daWarpmj_cFi */
void daWarpmj_c::initWarpArrive(int) {
    NOT_IMPLEMENTED;
}

/* 00000C94-00000CB8       .text actWarpArrive__10daWarpmj_cFi */
void daWarpmj_c::actWarpArrive(int) {
    NOT_IMPLEMENTED;
}

/* 00000CB8-00000D14       .text eventOrder__10daWarpmj_cFv */
void daWarpmj_c::eventOrder() {
    NOT_IMPLEMENTED;
}

/* 00000D14-00000DD0       .text checkOrder__10daWarpmj_cFv */
void daWarpmj_c::checkOrder() {
    NOT_IMPLEMENTED;
}

/* 00000DD0-00000E10       .text animPlay__10daWarpmj_cFv */
void daWarpmj_c::animPlay() {
    NOT_IMPLEMENTED;
}

/* 00000E10-00000E8C       .text setEndAnm__10daWarpmj_cFv */
void daWarpmj_c::setEndAnm() {
    NOT_IMPLEMENTED;
}

/* 00000E8C-00000EE0       .text getSeaY__10daWarpmj_cF4cXyz */
void daWarpmj_c::getSeaY(cXyz) {
    NOT_IMPLEMENTED;
}

/* 00000EE0-00000FDC       .text check_warp__10daWarpmj_cFv */
void daWarpmj_c::check_warp() {
    NOT_IMPLEMENTED;
}

/* 00000FDC-0000114C       .text _draw__10daWarpmj_cFv */
bool daWarpmj_c::_draw() {
    NOT_IMPLEMENTED;
    return 0;
}

/* 0000114C-0000116C       .text daWarpmj_Create__FPv */
static cPhs_State daWarpmj_Create(void* i_this) {
    return ((daWarpmj_c*)i_this)->_create();
}

/* 0000116C-00001190       .text daWarpmj_Delete__FPv */
static BOOL daWarpmj_Delete(void* i_this) {
    return ((daWarpmj_c*)i_this)->_delete();
}

/* 00001190-000011B4       .text daWarpmj_Draw__FPv */
static BOOL daWarpmj_Draw(void* i_this) {
    return ((daWarpmj_c*)i_this)->_draw();
}

/* 000011B4-000011D8       .text daWarpmj_Execute__FPv */
static BOOL daWarpmj_Execute(void* i_this) {
    return ((daWarpmj_c*)i_this)->_execute();
}

/* 000011D8-000011E0       .text daWarpmj_IsDelete__FPv */
static BOOL daWarpmj_IsDelete(void*) {
    return TRUE;
}

static actor_method_class daWarpmjMethodTable = {
    (process_method_func)daWarpmj_Create,
    (process_method_func)daWarpmj_Delete,
    (process_method_func)daWarpmj_Execute,
    (process_method_func)daWarpmj_IsDelete,
    (process_method_func)daWarpmj_Draw,
};

actor_process_profile_definition g_profile_WARPMAJYUU = {
    /* Layer ID     */ fpcLy_CURRENT_e,
    /* List ID      */ 0x0003,
    /* List Prio    */ fpcPi_CURRENT_e,
    /* Proc Name    */ fpcNm_WARPMAJYUU_e,
    /* Proc SubMtd  */ &g_fpcLf_Method.base,
    /* Size         */ sizeof(daWarpmj_c),
    /* Size Other   */ 0,
    /* Parameters   */ 0,
    /* Leaf SubMtd  */ &g_fopAc_Method.base,
    /* Draw Prio    */ fpcDwPi_WARPMAJYUU_e,
    /* Actor SubMtd */ &daWarpmjMethodTable,
    /* Status       */ fopAcStts_CULL_e | fopAcStts_UNK4000_e | fopAcStts_UNK40000_e,
    /* Group        */ fopAc_ACTOR_e,
    /* Cull Type    */ fopAc_CULLBOX_CUSTOM_e,
};
